- name: configure manager
  hosts: managers
  become: true
  gather_facts: false
  vars:
    rathole_type: ratholes
  roles:
    - common
    - rathole
    - syslog-srv
    - audit-srv
    - sudosh-srv

- name: configure honeypot
  hosts: honeypots
  become: true
  gather_facts: false
  vars:
    rathole_type: ratholec
  roles:
    - common
    - rathole
    - syslog-cli
    - audit-cli
    - sudosh-cli