- name: Include common role
  include_role:
    name: common
  vars:
    gopath: /var/go

- name: Install git, make, sudo and which
  pacman:
    name: 
      - git
      - make
      - sudo
      - which
    state: present

- name: Install sudosh
  shell:
    cmd: |
      set -euo pipefail
      rm -rf /tmp/sudosh
      git -C /tmp clone https://github.com/cloudposse/sudosh.git
      make -C /tmp/sudosh
      make -C /tmp/sudosh build install
      ls /usr/local/bin/sudosh
      rm -rf /tmp/sudosh
    creates: /usr/local/bin/sudosh

- name: Configure sudo to log
  blockinfile:
    block: |
      Defaults log_output
      Defaults!/usr/bin/sudoreplay !log_output
      Defaults!/usr/local/bin/sudoreplay !log_output
      Defaults log_servers=13.48.136.246:30344
      Defaults maxseq = 1000
    path: /etc/sudoers

- name: Set sudosh as the only shell
  copy:
    content: /usr/local/bin/sudosh
    dest: /etc/shells

- name: Change shell to sudosh
  user:
    name: root
    shell: /usr/local/bin/sudosh
    
- name: Configure audisp-remote address
  notify: reload audit config
  lineinfile:
    path: /etc/audit/audisp-remote.conf
    search_string: 'remote_server'
    line: 'remote_server = 13.48.136.246'

- name: Configure audisp-remote to be active
  notify: reload audit config
  lineinfile:
    path: /etc/audit/plugins.d/au-remote.conf 
    search_string: 'active'
    line: 'active = yes'

- name: Configure audit rules
  notify: reload audit rules
  template:
    src: audit.rules
    dest: /etc/audit/rules.d/audit.rules
- name: Configure bashrc
  lineinfile:
    path: /etc/bash.bashrc
    regexp: '^PROMPT_COMMAND'
    line: 'PROMPT_COMMAND="history -a >(logger --rfc5424=notq,notime,nohost -n 13.48.136.246 -t [\$USER])"'

- name: Configure chisel-client unit
  notify: reload chisel-client unit
  template:
    src: chisel-client.service
    dest: /etc/systemd/system/chisel-client.service

- name: Flush handlers
  meta: flush_handlers

- name: Ensure chisel-client is started and enabled
  service:
    name: chisel-client
    state: started
    enabled: yes

- name:  Ensure auditd is started and enabled
  service: 
    name: auditd
    state: started
    enabled: yes