- name: Include common role
  include_role:
    name: common
  vars:
    gopath: /var/go
    
- name: Configure audisp-remote address
  notify: reload audit config
  lineinfile:
    path: /etc/audit/audisp-remote.conf
    search_string: 'remote_server'
    line: 'remote_server = 13.48.136.246'

- name: Configure audisp-remote to be active
  notify: reload audit config
  lineinfile:
    path: /etc/audit/plugins.d/au-remote.conf 
    search_string: 'active'
    line: 'active = yes'

- name: Configure audit rules
  notify: reload audit rules
  template:
    src: audit.rules
    dest: /etc/audit/rules.d/audit.rules
- name: Configure bashrc
  lineinfile:
    path: /etc/bash.bashrc
    regexp: '^PROMPT_COMMAND'
    line: 'PROMPT_COMMAND="history -a >(logger --rfc5424=notq,notime,nohost -n 13.48.136.246 -t [\$USER])"'

- name: Configure chisel-client unit
  notify: reload chisel-client unit
  template:
    src: chisel-client.service
    dest: /etc/systemd/system/chisel-client.service

- name: Flush handlers
  meta: flush_handlers

- name: Ensure chisel-client is started and enabled
  service:
    name: chisel-client
    state: started
    enabled: yes

- name:  Ensure auditd is started and enabled
  service: 
    name: auditd
    state: started
    enabled: yes