- name: Install neovim, less, sudo from repo
  community.general.pacman:
    name: 
      - neovim
      - less
      - sudo
    state: present

- name: Add vim symlink
  command: 
    cmd: ln -s nvim /usr/bin/vim
    creates: "/usr/bin/vim"