- name: reload audit rules
  command: augenrules --load

- name: reload audit config
  shell: auditctl --signal stop; sleep 1; systemctl start auditd

- name: reload chisel-client unit
  command: systemctl daemon-reload
- name: reload chisel-client unit
  service:
    name: chisel-client
    state: restarted